# Generated by Django 3.2.7 on 2022-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
